ALTER TABLE "Product" ADD COLUMN "filamentGrams" INTEGER NOT NULL DEFAULT 187;
ALTER TABLE "Product" ADD COLUMN "printTimeMinutes" INTEGER NOT NULL DEFAULT 240;
ALTER TABLE "Product" ADD COLUMN "productionCost" INTEGER NOT NULL DEFAULT 90;
